---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-htmx-fiber-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:  
  project: default
  source:
    repoURL: https://igorsilva-dev.github.io/go_htmx_fiber_fullstack
    chart: go-htmx-fiber
    targetRevision: "*"
    helm:
      releaseName: go-htmx-fiber-dev
      values: |
        replicaCount: 3
        securityContext:
          runAsNonRoot: true
          fsGroup: 1000
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
        ingress:
          enabled: true
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
          - name: APP_ENV
            value: "production"
          - name: APP_PORT
            value: "8080"
          - name: DB_SSLMODE
            value: "require"
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 80
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        externalSecrets:
          enabled: true
          database-credentials:
            refreshInterval: 15m
            secretStoreRef:
              name: aws-secrets-store
              kind: SecretStore
            target:
              name: go-htmx-fiber-db-secrets
              template:
                data:
                  DB_HOST: "{{ .hostname }}"
                  DB_PORT: "{{ .port }}"
                  DB_USER: "{{ .username }}"
                  DB_PASSWORD: "{{ .password }}"
                  DB_NAME: "{{ .database }}"
            dataFrom:
              - extract:
                  key: development/go-htmx-fiber/database_credentials
          app-secrets:
            refreshInterval: 15m
            secretStoreRef:
              name: aws-secrets-store
              kind: SecretStore
            target:
              name: go-htmx-fiber-app-secrets
            data:
              - secretKey: CSRF_SECRET
                remoteRef:
                  key: development/go-htmx-fiber/csrf_secret
              - secretKey: SESSION_KEY
                remoteRef:
                  key: development/go-htmx-fiber/session_key
  destination:
    server: https://kubernetes.default.svc
    namespace: go-htmx-fiber  
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
